vich_uploader:
    db_driver: orm

    mappings:
        question_image:
            uri_prefix: ""
            upload_destination : '%kernel.project_dir%/public_html/images/questions'
            delete_on_remove: true
            delete_on_update: true
            namer:
                service:
                    Vich\UploaderBundle\Naming\UniqidNamer