vich_uploader:
    db_driver: orm

    mappings:
        question_image:
            uri_prefix: '/public/images/questions'
            upload_destination : '%kernel.project_dir%/public/images/questions'
            namer:
                service:
                    Vich\UploaderBundle\Naming\UniqidNamer